version: "3.2"
networks:
  zab_nw:
volumes:
  mysql_vol:
  zabbix_vol_enc:
  zabbix_vol_modules:
  zabbix_vol_usr:
  zabbix_vol_ssl:
  zabbix_vol_ssl_keys:
  zabbix_web_vol:
  zabbix_vol_snmptraps:
  zabbix_vol_mibs:
  zabbix_vol_ssl_ca:
  zabbix_vol_alert:
  zabbix_vol_agent_enc:
  zabbix_vol_agentd:
  zabbix_vol_agent_modules:
  zabbix_vol_ssh_keys:
services:
  mysql:
    image: nexus:5555/mysql:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - zab_nw
    ports:
      - "3306:3306"
    volumes:
      - mysql_vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
  zabbix-server:
    image: nexus:5555/zabbix-server-mysql:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "10051:10051"
    networks:
      - zab_nw
    volumes:
      - zabbix_vol_enc:/var/lib/zabbix/enc
      - zabbix_vol_ssl:/var/lib/zabbix/ssl/certs
      - zabbix_vol_ssl_keys:/var/lib/zabbix/ssl/keys
      - zabbix_vol_usr:/usr/lib/zabbix/externalscripts
      - zabbix_vol_modules:/var/lib/zabbix/modules
      - zabbix_vol_snmptraps:/var/lib/zabbix/snmptraps
      - zabbix_vol_mibs:/var/lib/zabbix/mibs
      - zabbix_vol_ssl_ca:/var/lib/zabbix/ssl/ssl_ca
      - zabbix_vol_alert:/usr/lib/zabbix/alertscripts
      - zabbix_vol_ssh_keys:/var/lib/zabbix/ssh_keys
          
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      DB_SERVER_HOST: "mysql"
      DB_SERVER_PORT: "3306"
  zabbix-web:
    image: 	nexus:5555/zabbix-web-nginx-mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "${ZBX_WEB_PORT}:80"
    networks:
      - zab_nw
    volumes:
      - zabbix_web_vol:/etc/ssl/nginx
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      DB_SERVER_HOST: "mysql"
      DB_SERVER_PORT: "3306"
      ZBX_SERVER_HOST: "zabbix-server"
