version: "3.2"
networks:
  zab_nw:
volumes:
  mysql_vol:
  zabbix_vol:
  zabbix_web_vol:
services:
  mysql:
    image: {Add New Image from DOCKERHUB} (mysql:latest)
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - zab_nw
    volumes:
      - mysql_vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
  zabbix-server:
    image: {Add New zabbix server image} - i.e (zabbix-server-mysql:latest)
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "10051:10051"
    networks:
      - zab_nw
    volumes:
      - zabbix_vol:/var/lib/zabbix
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      DB_SERVER_HOST: "mysql"
      DB_SERVER_PORT: "3306"
  zabbix-web:
    image: 	{Add New zabbix ngnix image} i.e (zabbix-web-nginx-mysql)
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "${ZBX_WEB_PORT}:80"
    networks:
      - zab_nw
    volumes:
      - zabbix_web_vol:/etc/ssl/nginx
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      DB_SERVER_HOST: "mysql"
      DB_SERVER_PORT: "3306"
      ZBX_SERVER_HOST: "zabbix-server"
  zabbix-agent-1:
    image: {Add New zabbix agent from dockerhub} i.e (zabbix-agent)
    deploy:
      replicas: 1 
      restart_policy:
        condition: on-failure
    networks:
      - zab_nw
    environment:
      ZBX_HOSTNAME: "zabbix-agent-1"
      ZBX_SERVER_HOST: "tasks.zabbix-server"
  zabbix-agent-2:
    image: {Add New zabbix agent from dockerhub} i.e (zabbix-agent)
    deploy:
      replicas: 1 
      restart_policy:
        condition: on-failure
    networks:
      - zab_nw
    environment:
      ZBX_HOSTNAME: "zabbix-agent-2"
      ZBX_SERVER_HOST: "tasks.zabbix-server"
